### Get all users
GET http://localhost:8080/users
Accept: application/json

###

### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Alan",
  "email": "alan@example.com"
}

###
DELETE http://localhost:8080/users/1

### Get user by ID (example with ID 1)
GET http://localhost:8080/users/1
Accept: application/json

###

### Update user by ID (example with ID 1)
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Alan Paccor",
  "email": "alanp@example.com"
}

###

### Delete user by ID (example with ID 1)
DELETE http://localhost:8080/users/1

